### ISSUE TITLE
Receive asset options required (Onchain or Lightening )

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#529]
- [ ] @Jddesigner0003 As per Discussion we will need option when user clicks on receive asset (on which they want to receive On-chain wallet or Lightening Wallet )

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/e51a6faf-d307-4d41-92a9-e653a474757c

**Comment by akshay8551** [comment]
@Deveshshankar and @Jddesigner0003 Could please check this flow again? Please confirm asset's details need or not. And also check is there need to asset's id and amount in two seperate screens.

I have added screen recording above. Please have look.


Thanks.

**Comment by Jddesigner0003** [comment]
@Deveshshankar @akshay8551  

Here’s the revised version with proper grammar and structure:

---

Hey everyone,  

Last time we discussed this flow, Utkarsh and Shushank agreed on it. Based on that, I designed the flow, got approval from the team, and then passed it on to your development team.  

As per my understanding, the flow works as follows:  

1. Creating Assets:  
   - The user can first create an asset by adding an address and then proceeding to create it.  

2. Viewing Asset Details:  
   - Once the asset is created, the user is redirected to the asset details screen.  

3. Receiving Assets:  
   - On the asset details screen, the user can select the Receive button.  
   - The user is then taken to the next screen, where they can choose how they want to receive the asset: On-Chain or Lightning. 

4. Adding Amount & Confirmation:  
   - Based on the user's selection, we provide a field for entering the amount.  
   - At the bottom of this screen, the user can confirm the details via a chatbox-style interface and then proceed.  

5. Invoice Screen:
   - Finally, the user sees the invoice address displayed as a QR code, which they can scan or copy as needed.  
   
Note: Devesh please advice me if i am wrong then i will change in UI otherwise akashy you can do it as per i explain 

![image](https://github.com/user-attachments/assets/6af86207-b252-40b4-8586-a6f5d19682f3)

**Comment by Deveshshankar** [comment]
@Jddesigner0003 Please update this as per discussion and changes done

**Comment by Jddesigner0003** [comment]
@akshay8551   please check the flow 

Figma: https://www.figma.com/design/e0RxSAiRCMt5Z48LJVNEXr/Tribe-RGB?node-id=4530-14137&t=bTmU2RIct1LU34VV-1

<img width="3830" alt="Send Sats Onchain Flow" src="https://github.com/user-attachments/assets/d5365839-004d-43d3-b8ef-dadf778fe921">

**Comment by akshay8551** [comment]
@Jddesigner0003 , You put wrong url in this issue. Issue's description and issue is different . As per our discussion (Standup call) we resolved this issue. So I'm going to mark it fixed.

Thanks

**Comment by Deveshshankar** [comment]
Completed
